directories:
  output: build-electron
  buildResources: build
appId: com.ereader.app
productName: E-Reader
extends: null
files:
  - filter:
      - ./build/**/*
      - ./main.js
      - ./package.json
win:
  icon: icon.ico
nsis:
  oneClick: false
  allowElevation: true
  allowToChangeInstallationDirectory: true
  installerIcon: icon.ico
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 8.5.0
